import {
  AdminHelmet,
  DeveloperHelmet,
  OrganiserHelmet,
  QaHelmet,
  UiUxHelmet,
} from "@/components/DeveloperHelmet";
import { DarkCard, LightCard } from "@/components/LightCard";
import {
  TheArtist,
  TheChampion,
  TheExaminer,
  TheGuardian,
  TheInnovator,
  TheInspirer,
  TheLeader,
  TheObserver,
  TheOrganiser,
  ThePerfectionist,
  ThePerformer,
  ThePioneer,
  TheResolver,
  TheTactician,
  TheVisionary,
} from "@/components/TheGuardian";
import { OutcomeType } from "@/types/test";

export const outcomes: {
  [key: string]: OutcomeType;
} = {
  INFJ: {
    code: "INFJ",
    title: "The Guardian",
    category: "SD",
    pColor: "#48BD80",
    Content: TheGuardian,
    HelmetElement: DeveloperHelmet,
    CardElement: LightCard,
  },
  INTJ: {
    code: "INTJ",
    title: "The Visionary",
    category: "SD",
    pColor: "#126094",
    Content: TheVisionary,
    HelmetElement: DeveloperHelmet,
    CardElement: LightCard,
  },
  INTP: {
    code: "INTP",
    title: "The Pioneer",
    category: "SD",
    pColor: "#7B3C57",
    Content: ThePioneer,
    HelmetElement: DeveloperHelmet,
    CardElement: LightCard,
  },
  ENTP: {
    code: "ENTP",
    title: "The Innovator",
    category: "SD",
    pColor: "#8095BE",
    Content: TheInnovator,
    HelmetElement: DeveloperHelmet,
    CardElement: LightCard,
  },
  ENFJ: {
    code: "ENFJ",
    title: "The Leader",
    category: "SD",
    pColor: "#303E50",
    Content: TheLeader,
    HelmetElement: DeveloperHelmet,
    CardElement: LightCard,
  },
  ISFJ: {
    code: "ISFJ",
    title: "The Observer",
    category: "UIUX",
    pColor: "#E2007C",
    Content: TheObserver,
    HelmetElement: UiUxHelmet,
    CardElement: LightCard,
  },
  ISFP: {
    code: "ISFP",
    title: "The Artist",
    category: "UIUX",
    pColor: "#D66451",
    Content: TheArtist,
    HelmetElement: UiUxHelmet,
    CardElement: LightCard,
  },
  ENFP: {
    code: "ENFP",
    title: "The Inspirer",
    category: "UIUX",
    pColor: "#012A7C",
    Content: TheInspirer,
    HelmetElement: UiUxHelmet,
    CardElement: LightCard,
  },
  "INFP ": {
    code: "INFP",
    title: "The Champion",
    category: "UIUX",
    pColor: "#304D3B",
    Content: TheChampion,
    HelmetElement: UiUxHelmet,
    CardElement: LightCard,
  },
  ISTJ: {
    code: "ISTJ",
    title: "The Perfectionist",
    category: "QA",
    pColor: "#09B1D8",
    Content: ThePerfectionist,
    HelmetElement: QaHelmet,
    CardElement: LightCard,
  },
  ESTJ: {
    code: "ESTJ",
    title: "The Organiser",
    category: "QA",
    pColor: "#DA515E",
    Content: TheOrganiser,
    HelmetElement: OrganiserHelmet,
    CardElement: LightCard,
  },
  ESFJ: {
    code: "ESFJ",
    title: "The Examiner",
    category: "QA",
    pColor: "#9A6DE2",
    Content: TheExaminer,
    HelmetElement: QaHelmet,
    CardElement: LightCard,
  },
  ISTP: {
    code: "ISTP",
    title: "The Tactician",
    category: "Admin",
    pColor: "#FFA349",
    Content: TheTactician,
    HelmetElement: AdminHelmet,
    CardElement: DarkCard,
  },
  ESTP: {
    code: "ESTP",
    title: "The Resolver",
    category: "Admin",
    pColor: "#F781CC",
    Content: TheResolver,
    HelmetElement: AdminHelmet,
    CardElement: DarkCard,
  },
  ESFP: {
    code: "ESFP",
    title: "The Performer",
    category: "Admin",
    pColor: "#4E4164",
    Content: ThePerformer,
    HelmetElement: AdminHelmet,
    CardElement: DarkCard,
  },
};
